### ISSUE TITLE
Demo page different from code provided?

### ISSUE THREAD

**Issue by jlahijani** [CodyHouse/cd-main-header-v2-changelog#1]
Demo JS is here:
https://codyhouse.co/app/components/source/main-header-v2/dist/main-header-v2.min.js?v=41

Provided JS is here:
https://codyhouse.co/ds/components/info/main-header-v2

The Demo JS has references to `x-rem` etc while the Provided JS does not.  Are they out of sync?

When using the provided code, I my navbar does not sticky when scrolling down.

**Comment by claudia-romano** [comment]
Hi there,
in the component demo page we minify HTML, CSS and JavaScript and shorten class names. This is why you see references to classes like `x-rem`. 

You should use only the code that we provide in the Info page/Demo page of the component (using the View Code action button):
https://codyhouse.co/ds/components/info/main-header-v2
https://codyhouse.co/ds/components/app/main-header-v2

Cheers
